bootstrapServers: pkc-mxqvx.europe-southwest1.gcp.confluent.cloud:9092
chuckClientId: chuck-stats-consumer
chuckGroupId: chuck-stats-cg
chuckTopic: chuck-fact-topic
statsTopic: chuck-stats-topic
autoOffsetReset: earliest