bootstrapServers: pkc-mxqvx.europe-southwest1.gcp.confluent.cloud:9092
inputTopic: chuck-fact-topic
outputTopic: chuck-wordcount-topic
tempStateDir: $APP_HOME/tmp
processingGuaranteeConfig: exactly_once_v2