appPort: 38081
bootstrapServers: broker:29092
chuckClientId: chuck-java-consumer
chuckGroupId: chuck-java-cg
chuckTopic: chuck-java-topic
wordCountClientId: word-cound-id
wordCountTopic: word-count
wordCountGroupId: word-count-cg
schemaRegistryUrl: http://schema-registry:8081